const prisma = require("../db/prisma");
const storage = require("../storage");

const MAX_DAYS = 30;

// Turn "1d", "10d", "12h" into milliseconds. null = invalid input.
function parseDuration(input) {
  const m = /^(\d+)([dh])$/.exec((input || "").trim());
  if (!m) return null;
  const n = Number(m[1]);
  if (n <= 0) return null;
  const ms = m[2] === "d" ? n * 86400000 : n * 3600000;
  if (ms > MAX_DAYS * 86400000) return null; // cap how long a link can live
  return ms;
}

// POST /folders/:id/share — owner creates a time-limited public link.
async function createShare(req, res) {
  const folderId = Number(req.params.id);

  // Only the owner may share their folder.
  const folder = await prisma.folder.findFirst({
    where: { id: folderId, userId: req.user.id },
  });
  if (!folder) return res.status(404).render("error", {
    title: "Not found", status: 404, message: "Folder not found.",
  });

  const ms = parseDuration(req.body.duration);
  if (ms === null) return res.status(400).render("error", {
    title: "Bad duration", status: 400, message: "Use a duration like 1d, 7d, or 12h (max 30d).",
  });

  // The uuid id is generated by the schema's @default(uuid()) — that's the secret.
  await prisma.share.create({
    data: { folderId, expiresAt: new Date(Date.now() + ms) },
  });
  res.redirect(`/folders/${folderId}`);
}

// POST /folders/:id/shares/:shareId/delete — revoke a link.
async function revokeShare(req, res) {
  // deleteMany scoped through the folder's owner: you can only revoke your own.
  await prisma.share.deleteMany({
    where: { id: req.params.shareId, folder: { userId: req.user.id } },
  });
  res.redirect(`/folders/${req.params.id}`);
}

// GET /share/:token — PUBLIC. No auth. Anyone with the link.
async function sharedFolder(req, res) {
  const share = await prisma.share.findUnique({
    where: { id: req.params.token },
    include: { folder: { include: { files: { orderBy: { uploadedAt: "desc" } } } } },
  });

  // Not found OR expired → same generic message (don't reveal which).
  if (!share || share.expiresAt < new Date()) {
    return res.status(404).render("error", {
      title: "Link expired", status: 404, message: "This share link is invalid or has expired.",
    });
  }

  res.render("shared/folder", { title: share.folder.name, share, folder: share.folder });
}

// GET /share/:token/files/:fileId/download — PUBLIC download.
async function sharedDownload(req, res) {
  const share = await prisma.share.findUnique({ where: { id: req.params.token } });
  if (!share || share.expiresAt < new Date()) {
    return res.status(404).render("error", {
      title: "Link expired", status: 404, message: "This share link is invalid or has expired.",
    });
  }

  // CRITICAL: the file must live in THIS shared folder. Without the folderId
  // check, a valid token could download any file in the app by guessing ids.
  const file = await prisma.file.findFirst({
    where: { id: Number(req.params.fileId), folderId: share.folderId },
  });
  if (!file) return res.status(404).render("error", {
    title: "Not found", status: 404, message: "File not found.",
  });

  res.redirect(storage.downloadUrl(file));
}

module.exports = { createShare, revokeShare, sharedFolder, sharedDownload };
